import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const { data, isLoading } = trpc.useQuery(["hello", { text: "Ivan" }]);

  if (isLoading) return <div>Loading...</div>;

  if (data) return <div>{data.greeting}</div>;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen w-screen flex flex-col justify-center items-center">
        <div className="text-2xl text-center">Which Pokémon is Rounder?</div>
        <div className="p-4" />
        <div className="border rounded p-8 flex justify-between max-w-7xl items-center">
          <div className="w-16  h-16 bg-slate-300" />
          <div className="p-8">Vs</div>
          <div className="w-16 h-16 bg-red-500" />
        </div>
      </div>
    </div>
  );
};

export default Home;
